version: "2"

linters:
  default: none
  enable:
    - revive
    - govet
    - unconvert
    - staticcheck
    - unused
    - gosec
    - gocyclo
    - dupl
    - misspell
    - unparam
    - ineffassign
    - gochecknoinits
    - gocritic
    - nakedret
    - prealloc
  exclusions:
    presets:
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: "weak cryptographic primitive"
      - linters:
          - revive
        path: _test\.go$
      - linters:
          - unparam
          - unused
        path: _test\.go$

  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy

run:
  concurrency: 4
  timeout: 5m

formatters:
  enable:
    - gofmt
