version: '2'
services:
  rlb:
    build: .
    image: umputun/rlb:latest
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    hostname: rlb
    restart: always
    container_name: rlb

    ports:
    - 7070:7070

    volumes:
    - ./rlb-sample.yml:/srv/rlb.yml

    environment:
    - CONF=/srv/rlb.yml
    - TIMEOUT=10s
    - REFRESH=60s
    - DEBUG=true
